CREATE TABLE "Customer" (
  "customer_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar,
  "first_name" varchar,
  "last_name" varchar,
  "customer_created" date,
  "segment_id" int
);

CREATE TABLE "Marketing_consent" (
  "consent_id" int PRIMARY KEY,
  "customer_id" int,
  "channel" varchar,
  "consent" bool NOT NULL,
  "consent_updated" datetime
);

CREATE TABLE "Membership_tier" (
  "customer_id" int PRIMARY KEY,
  "member_level" varchar,
  "level_start" date,
  "level_end" date
);

CREATE TABLE "Lifecycle_segment" (
  "segment_id" int PRIMARY KEY,
  "description" varchar
);

CREATE TABLE "Lifecycle_segment_history" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customer_id" int,
  "segment_id" int,
  "start_date" date,
  "end_date" date
);

CREATE TABLE "Campaign" (
  "campaign_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "campaign_name" varchar,
  "campaign_type" varchar,
  "channel" varchar,
  "start_date" date,
  "end_date" date,
  "has_coupon" bool,
  "budget" decimal
);

CREATE TABLE "Campaign_utm" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "campaign_id" int,
  "utm_source" varchar,
  "utm_medium" varchar,
  "utm_campaign" varchar,
  "utm_content" varchar
);

CREATE TABLE "Email_delivery" (
  "delivery_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "campaign_id" int,
  "customer_id" int,
  "segment_id" int,
  "message number" int,
  "delivery_time" datetime,
  "opening_time" datetime,
  "click_time" datetime,
  "is_control_group" bool
);

CREATE TABLE "Paid_media_delivery" (
  "paid_media_delivery_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "campaign_id" int,
  "platform" varchar,
  "ad_name" varchar,
  "impressions" int,
  "clicks" int,
  "spend" decimal,
  "delivery_date" date
);

CREATE TABLE "Conversion" (
  "conversion_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "delivery_id" int,
  "paid_media_delivery_id" int,
  "conversion_type" varchar,
  "transaction_id" int,
  "coupon_code_used" boolean
);

CREATE TABLE "Revenue" (
  "transaction_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customer_id" int,
  "transaction_date" date,
  "transaction" decimal,
  "sales_channel" varchar
);

ALTER TABLE "Marketing_consent" ADD FOREIGN KEY ("customer_id") REFERENCES "Customer" ("customer_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Customer" ADD FOREIGN KEY ("customer_id") REFERENCES "Membership_tier" ("customer_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Revenue" ADD FOREIGN KEY ("customer_id") REFERENCES "Customer" ("customer_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Campaign_utm" ADD FOREIGN KEY ("campaign_id") REFERENCES "Campaign" ("campaign_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Email_delivery" ADD FOREIGN KEY ("campaign_id") REFERENCES "Campaign" ("campaign_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Email_delivery" ADD FOREIGN KEY ("customer_id") REFERENCES "Customer" ("customer_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Conversion" ADD FOREIGN KEY ("delivery_id") REFERENCES "Email_delivery" ("delivery_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Customer" ADD FOREIGN KEY ("segment_id") REFERENCES "Lifecycle_segment" ("segment_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Lifecycle_segment_history" ADD FOREIGN KEY ("customer_id") REFERENCES "Customer" ("customer_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Conversion" ADD FOREIGN KEY ("transaction_id") REFERENCES "Revenue" ("transaction_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Email_delivery" ADD FOREIGN KEY ("segment_id") REFERENCES "Lifecycle_segment" ("segment_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Lifecycle_segment_history" ADD FOREIGN KEY ("segment_id") REFERENCES "Lifecycle_segment" ("segment_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Paid_media_delivery" ADD FOREIGN KEY ("campaign_id") REFERENCES "Campaign" ("campaign_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Conversion" ADD FOREIGN KEY ("paid_media_delivery_id") REFERENCES "Paid_media_delivery" ("paid_media_delivery_id") DEFERRABLE INITIALLY IMMEDIATE;
